// ============================================================
// MOCK DATA — замените на реальные запросы к вашему backend
// Структура объекта фильма:
// {
//   id: number,
//   title: string,
//   year: number,
//   duration: string,
//   rating: number,
//   votes: number,
//   views: number,
//   ageRating: string,
//   poster: string,          // URL постера
//   trailerUrl: string,      // YouTube embed URL
//   genres: string[],        // массив жанров
//   countries: string[],     // массив стран
//   translation: string,     // тип перевода
//   description: string,
//   tags: string[],
//   isNew: boolean,
//   isPopular: boolean
// }
// ============================================================

const MOVIES_DATA = [
  {
    id: 1,
    title: "Паразити",
    year: 2019,
    duration: "2г 12хв",
    rating: 8.6,
    votes: 312,
    views: 8300,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    trailerUrl: "https://www.youtube.com/embed/5xH0HfJHsaY",
    genres: ["Трилер", "Драма", "Комедія"],
    countries: ["Південна Корея"],
    translation: "Дубляж",
    description: "Неблагополучна сім'я Кі-Тхека складається з нероб і невдах. Живучи в напівпідвальному приміщенні, усі мріють стати багатими й незалежними. Одного разу товариш одного з членів сім'ї пропонує Кі-у влаштуватися на роботу до однієї заможної сімейки бізнесмена містера Пака.",
    tags: ["Про життя", "Герої", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 2,
    title: "Джокер",
    year: 2019,
    duration: "2г 2хв",
    rating: 8.4,
    votes: 521,
    views: 12400,
    ageRating: "18+",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    trailerUrl: "https://www.youtube.com/embed/zAGVQLHvwOY",
    genres: ["Трилер", "Драма", "Злочин"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Артур Флек — невдаха-клоун, що мешкає з хворою матір'ю в Готем-Сіті. Після серії принизливих невдач він поступово перетворюється на злочинця, відомого як Джокер.",
    tags: ["Герої", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 3,
    title: "Дюна: Частина перша",
    year: 2021,
    duration: "2г 35хв",
    rating: 8.0,
    votes: 289,
    views: 9800,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklpcvweasySMonaqgIOkMA.jpg",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    genres: ["Фантастика", "Пригоди", "Драма"],
    countries: ["США", "Канада"],
    translation: "Дубляж",
    description: "Пол Атрейдес — молодий чоловік із знатного роду, що стає ключовою фігурою у боротьбі за найцінніший ресурс всесвіту — спайс, що видобувається на пустельній планеті Арракіс.",
    tags: ["Прем'єри", "Герої"],
    isNew: true,
    isPopular: true
  },
  {
    id: 4,
    title: "Не дивись вгору",
    year: 2021,
    duration: "2г 18хв",
    rating: 7.2,
    votes: 178,
    views: 7600,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg",
    trailerUrl: "https://www.youtube.com/embed/RbIxYm3mKzI",
    genres: ["Комедія", "Драма", "Фантастика"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Два астрономи відправляються у медіатур, намагаючись попередити людство про наближення астероїда, що знищить Землю.",
    tags: ["Про життя", "Прем'єри"],
    isNew: true,
    isPopular: false
  },
  {
    id: 5,
    title: "Матриця: Воскресіння",
    year: 2021,
    duration: "2г 28хв",
    rating: 5.7,
    votes: 203,
    views: 6200,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditjonkE3LB.jpg",
    trailerUrl: "https://www.youtube.com/embed/9ix7TUGVYIo",
    genres: ["Фантастика", "Бойовик", "Пригоди"],
    countries: ["США", "Австралія", "Великобританія"],
    translation: "Дубляж",
    description: "Томас Андерсон живе звичайним життям, але щось не так. Він знову зустрічає Тринітті і починає сумніватися у реальності навколишнього світу.",
    tags: ["Герої", "Прем'єри"],
    isNew: true,
    isPopular: false
  },
  {
    id: 6,
    title: "Людина-Павук: Немає шляху додому",
    year: 2021,
    duration: "2г 28хв",
    rating: 8.2,
    votes: 445,
    views: 15300,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    trailerUrl: "https://www.youtube.com/embed/JfVOs4VSpmA",
    genres: ["Бойовик", "Пригоди", "Фантастика"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Після того як особистість Пітера Паркера розкрита, він просить Доктора Стрейнджа допомогти йому. Але заклинання йде не так, як планувалось.",
    tags: ["Герої", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 7,
    title: "Батьківщина",
    year: 2021,
    duration: "1г 58хв",
    rating: 7.5,
    votes: 134,
    views: 4800,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    trailerUrl: "https://www.youtube.com/embed/ux9M_9Hy5kc",
    genres: ["Драма", "Трилер"],
    countries: ["Україна"],
    translation: "Оригінал",
    description: "Молодий чоловік повертається додому після довгої відсутності і виявляє, що його рідне місто змінилося до невпізнання.",
    tags: ["Про життя"],
    isNew: false,
    isPopular: false
  },
  {
    id: 8,
    title: "Вічні",
    year: 2021,
    duration: "2г 37хв",
    rating: 6.3,
    votes: 267,
    views: 8100,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/6TPZSJ06OEXehlEGCdMO8OVOPYA.jpg",
    trailerUrl: "https://www.youtube.com/embed/BIhNsAtPbPI",
    genres: ["Бойовик", "Пригоди", "Фантастика"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Раса безсмертних надлюдей, що живуть на Землі тисячоліттями, змушена знову об'єднатися після подій Месників.",
    tags: ["Герої"],
    isNew: false,
    isPopular: true
  },
  {
    id: 9,
    title: "Шан-Чі та легенда десяти кілець",
    year: 2021,
    duration: "2г 12хв",
    rating: 7.4,
    votes: 198,
    views: 7200,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    trailerUrl: "https://www.youtube.com/embed/8YjFbMbfXaQ",
    genres: ["Бойовик", "Пригоди", "Фантастика"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Шан-Чі змушений зіткнутися зі своїм минулим, коли його втягують у таємничу організацію Десяти Кілець.",
    tags: ["Герої", "Прем'єри"],
    isNew: false,
    isPopular: true
  },
  {
    id: 10,
    title: "Чорна Вдова",
    year: 2021,
    duration: "2г 14хв",
    rating: 6.7,
    votes: 312,
    views: 9400,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    trailerUrl: "https://www.youtube.com/embed/Fp9pNPdNwjI",
    genres: ["Бойовик", "Пригоди", "Трилер"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Наташа Романова зіштовхується зі своїм минулим і небезпечною змовою, пов'язаною з програмою Червона Кімната.",
    tags: ["Герої"],
    isNew: false,
    isPopular: true
  },
  {
    id: 11,
    title: "Гра в кальмара",
    year: 2021,
    duration: "1г 0хв",
    rating: 8.0,
    votes: 567,
    views: 22100,
    ageRating: "18+",
    poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    trailerUrl: "https://www.youtube.com/embed/oqxAJKy0ii4",
    genres: ["Трилер", "Драма", "Бойовик"],
    countries: ["Південна Корея"],
    translation: "Дубляж",
    description: "Сотні людей з фінансовими труднощами отримують запрошення взяти участь у дитячих іграх. Переможець отримає величезний грошовий приз, але програш означає смерть.",
    tags: ["Про життя", "Герої"],
    isNew: false,
    isPopular: true
  },
  {
    id: 12,
    title: "Дюна: Частина друга",
    year: 2024,
    duration: "2г 46хв",
    rating: 8.5,
    votes: 423,
    views: 18700,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    genres: ["Фантастика", "Пригоди", "Драма"],
    countries: ["США", "Канада"],
    translation: "Дубляж",
    description: "Пол Атрейдес об'єднується з Чані та фременами, ведучи священну війну проти змовників, що знищили його сім'ю.",
    tags: ["Прем'єри", "Герої"],
    isNew: true,
    isPopular: true
  },
  {
    id: 13,
    title: "Оппенгеймер",
    year: 2023,
    duration: "3г 0хв",
    rating: 8.4,
    votes: 678,
    views: 19200,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    genres: ["Біографія", "Драма", "Історія"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Розповідь про американського фізика Дж. Роберта Оппенгеймера та його роль у розробці атомної бомби під час Другої світової війни.",
    tags: ["Про життя", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 14,
    title: "Барбі",
    year: 2023,
    duration: "1г 54хв",
    rating: 6.9,
    votes: 489,
    views: 16800,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8vlbzfAVF9Kp5fmHDOCOc.jpg",
    trailerUrl: "https://www.youtube.com/embed/pBk4NYhWNMM",
    genres: ["Комедія", "Пригоди", "Фентезі"],
    countries: ["США", "Великобританія", "Австралія"],
    translation: "Дубляж",
    description: "Барбі переживає екзистенційну кризу і разом з Кеном відправляється у реальний світ, щоб знайти відповіді на свої питання.",
    tags: ["Про життя", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 15,
    title: "Гладіатор 2",
    year: 2024,
    duration: "2г 28хв",
    rating: 7.1,
    votes: 234,
    views: 11300,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    trailerUrl: "https://www.youtube.com/embed/b2ZakFxSPdc",
    genres: ["Бойовик", "Пригоди", "Драма"],
    countries: ["США", "Великобританія", "Мальта"],
    translation: "Дубляж",
    description: "Нумерій Ацій Марк, що виріс у провінції Нумідія, потрапляє в полон і стає гладіатором, прагнучи помститися тим, хто знищив його дім.",
    tags: ["Герої", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 16,
    title: "Інтерстеллар",
    year: 2014,
    duration: "2г 49хв",
    rating: 8.6,
    votes: 892,
    views: 31400,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    genres: ["Фантастика", "Драма", "Пригоди"],
    countries: ["США", "Великобританія", "Канада"],
    translation: "Дубляж",
    description: "Команда дослідників подорожує крізь червоточину в пошуках нового дому для людства, поки Земля вмирає.",
    tags: ["Про життя", "Герої"],
    isNew: false,
    isPopular: true
  },
  {
    id: 17,
    title: "Початок",
    year: 2010,
    duration: "2г 28хв",
    rating: 8.8,
    votes: 1024,
    views: 28700,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    genres: ["Фантастика", "Бойовик", "Пригоди"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Злодій, що спеціалізується на крадіжці корпоративних секретів через технологію проникнення у сни, отримує завдання посіяти ідею у свідомості генерального директора.",
    tags: ["Герої", "Прем'єри"],
    isNew: false,
    isPopular: true
  },
  {
    id: 18,
    title: "Темний лицар",
    year: 2008,
    duration: "2г 32хв",
    rating: 9.0,
    votes: 1456,
    views: 42300,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
    genres: ["Бойовик", "Злочин", "Драма"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Бетмен піднімає ставки у своїй боротьбі з злочинністю. Маючи допомогу лейтенанта Джима Гордона та прокурора Гарві Дента, він вступає у протистояння з Джокером.",
    tags: ["Герої"],
    isNew: false,
    isPopular: true
  },
  {
    id: 19,
    title: "Форрест Гамп",
    year: 1994,
    duration: "2г 22хв",
    rating: 8.8,
    votes: 1123,
    views: 35600,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    trailerUrl: "https://www.youtube.com/embed/bLvqoHBptjg",
    genres: ["Драма", "Романтика", "Комедія"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Форрест Гамп — простодушний чоловік з низьким IQ, але добрим серцем. Він мимоволі стає свідком і учасником ключових подій американської історії.",
    tags: ["Про життя"],
    isNew: false,
    isPopular: true
  },
  {
    id: 20,
    title: "Список Шиндлера",
    year: 1993,
    duration: "3г 15хв",
    rating: 9.0,
    votes: 987,
    views: 18900,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    trailerUrl: "https://www.youtube.com/embed/gG22XNhtnoY",
    genres: ["Біографія", "Драма", "Історія"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Оскар Шиндлер — австрійський бізнесмен, що рятує понад тисячу польських євреїв від Голокосту, наймаючи їх на роботу на своїх заводах.",
    tags: ["Про життя"],
    isNew: false,
    isPopular: false
  },
  {
    id: 21,
    title: "Аватар: Шлях води",
    year: 2022,
    duration: "3г 12хв",
    rating: 7.6,
    votes: 534,
    views: 24100,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    trailerUrl: "https://www.youtube.com/embed/a8Gx8wiNbs8",
    genres: ["Фантастика", "Пригоди", "Бойовик"],
    countries: ["США", "Нова Зеландія"],
    translation: "Дубляж",
    description: "Джейк Саллі та Нейтірі створили сім'ю і роблять все можливе, щоб залишатися разом. Але їм доводиться покинути рідний дім і досліджувати регіони Пандори.",
    tags: ["Прем'єри", "Герої"],
    isNew: true,
    isPopular: true
  },
  {
    id: 22,
    title: "Топ Ган: Меверік",
    year: 2022,
    duration: "2г 10хв",
    rating: 8.3,
    votes: 612,
    views: 21800,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTHOmVUM0ziB90nHze5c4t.jpg",
    trailerUrl: "https://www.youtube.com/embed/giXco2jaZ_4",
    genres: ["Бойовик", "Драма"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Після понад 30 років служби Піт Меверік Мітчелл залишається льотчиком-випробувачем, уникаючи підвищення, яке виведе його з кабіни.",
    tags: ["Герої", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 23,
    title: "Все скрізь і одразу",
    year: 2022,
    duration: "2г 19хв",
    rating: 7.8,
    votes: 345,
    views: 13600,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    trailerUrl: "https://www.youtube.com/embed/wxN1T1uxQ2g",
    genres: ["Бойовик", "Пригоди", "Комедія"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Жінка середнього віку потрапляє у пригоду, де вона одна може врятувати світ, досліджуючи інші всесвіти і з'єднуючись з життями, якими вона могла б жити.",
    tags: ["Про життя", "Прем'єри"],
    isNew: true,
    isPopular: true
  },
  {
    id: 24,
    title: "Бетмен",
    year: 2022,
    duration: "2г 56хв",
    rating: 7.8,
    votes: 478,
    views: 17400,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    trailerUrl: "https://www.youtube.com/embed/mqqft2x_Aa4",
    genres: ["Бойовик", "Злочин", "Драма"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Коли маніяк-вбивця починає полювати на еліту Готема, Бетмен змушений розслідувати темне підпілля міста і поставити під сумнів свою сім'ю.",
    tags: [],
    isNew: true,
    isPopular: true
  },
  {
    id: 25,
    title: "Жахи в Амітівіллі",
    year: 2005,
    duration: "1г 52хв",
    rating: 6.2,
    votes: 234,
    views: 5600,
    ageRating: "18+",
    poster: "https://image.tmdb.org/t/p/w500/xKHkbAcnxJKOHSMWjKbV4BYfNdR.jpg",
    trailerUrl: "https://www.youtube.com/embed/U1fu8V2yvFY",
    genres: ["Жахи", "Драма"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Молода сім'я переїжджає в красивий будинок, але незабаром розуміє, що він насичений темною енергією і жахливою історією.",
    tags: [],
    isNew: false,
    isPopular: false
  },
  {
    id: 26,
    title: "Наша планета",
    year: 2019,
    duration: "8 епізодів",
    rating: 9.0,
    votes: 567,
    views: 12300,
    ageRating: "6+",
    poster: "https://image.tmdb.org/t/p/w500/tZjrHodwe2vDJtmKYHKLDXoIvNf.jpg",
    trailerUrl: "https://www.youtube.com/embed/JSkYbEDWaAI",
    genres: ["Документальний", "Природа"],
    countries: ["Великобританія"],
    translation: "Дубляж",
    description: "Епічна подорож по світу, яка показує найбільш видатні природні явища і дикої природи нашої планети.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 27,
    title: "Ваше Ім'я",
    year: 2016,
    duration: "1г 46хв",
    rating: 8.4,
    votes: 456,
    views: 9800,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/xq1Ngq7d2HsqyRwxQrjc7Sml32w.jpg",
    trailerUrl: "https://www.youtube.com/embed/3KR8_igQOm0",
    genres: ["Анімація", "Романтика", "Драма"],
    countries: ["Японія"],
    translation: "Дубляж",
    description: "Два незнайомці раптово починають обмінюватися тілами через містичний зв'язок. Вони повинні розібратися в цій дивній ситуації.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 28,
    title: "Зоотопія",
    year: 2016,
    duration: "1г 48хв",
    rating: 8.0,
    votes: 567,
    views: 13400,
    ageRating: "6+",
    poster: "https://image.tmdb.org/t/p/w500/mGlRvM1gIf6gxV9ydcXYYvKv1Dn.jpg",
    trailerUrl: "https://www.youtube.com/embed/bvxJ0DwWH84",
    genres: ["Сімейний", "Комедія", "Анімація"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Молода крольчиця-поліцейський приїжджає в місто Зоотопія, щоб розслідувати справу, яка змінить її життя.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 29,
    title: "Величезна Шоумен",
    year: 2017,
    duration: "1г 45хв",
    rating: 8.0,
    votes: 567,
    views: 11200,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/mWeMd01mwEGGFnKWtg9wg3802Ow.jpg",
    trailerUrl: "https://www.youtube.com/embed/ic7mCjAwYB0",
    genres: ["Мюзикл", "Драма", "Комедія"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Історія про P.T. Barnum, який створив найбільший цирк у світі та змінив розваги назавжди.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 30,
    title: "Шерлок Холмс",
    year: 2009,
    duration: "2г 8хв",
    rating: 7.6,
    votes: 456,
    views: 8900,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/8ayuZ8Oy5yvjvNlV1SHr6UJFQXw.jpg",
    trailerUrl: "https://www.youtube.com/embed/nnGdJasXRyI",
    genres: ["Детектив", "Бойовик", "Драма"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Легендарний детектив Шерлок Холмс розслідує таємничу справу, яка вимагає всіх його дедуктивних навичок.",
    tags: [],
    isNew: false,
    isPopular: false
  },
  {
    id: 31,
    title: "Три жестоких",
    year: 2007,
    duration: "1г 56хв",
    rating: 7.4,
    votes: 234,
    views: 5200,
    ageRating: "16+",
    poster: "https://image.tmdb.org/t/p/w500/fVCJsdUNY85dBWSwQtVSIvVeiMc.jpg",
    trailerUrl: "https://www.youtube.com/embed/Ym0PcWbVJAw",
    genres: ["Вестерн", "Бойовик", "Драма"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Три легендарні ковбої зустрічаються для останнього протистояння в дикому західу.",
    tags: [],
    isNew: false,
    isPopular: false
  },
  {
    id: 32,
    title: "Крід: Спадщина Роккі",
    year: 2015,
    duration: "2г 12хв",
    rating: 7.3,
    votes: 345,
    views: 7600,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/mCfwqcEo8d1prevBMARPnX0EH5R.jpg",
    trailerUrl: "https://www.youtube.com/embed/Ee_uujKuJMM",
    genres: ["Спорт", "Драма", "Бойовик"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Молодий боксер отримує шанс боксувати проти чемпіона світу, дотримуючись спадщини Роккі Бальбоа.",
    tags: [],
    isNew: false,
    isPopular: false
  },
  {
    id: 33,
    title: "Дюнкерк",
    year: 2017,
    duration: "1г 46хв",
    rating: 7.8,
    votes: 567,
    views: 10400,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/cxseHQr_J7QvkZoa23Te_dBUVK8.jpg",
    trailerUrl: "https://www.youtube.com/embed/F-eMt3SrfFU",
    genres: ["Військовий", "Драма", "Історія"],
    countries: ["США", "Великобританія"],
    translation: "Дубляж",
    description: "Епічна розповідь про евакуацію союзних військ з пляжу Дюнкерка під час Другої світової війни.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 34,
    title: "Шостий сенс",
    year: 1999,
    duration: "1г 47хв",
    rating: 8.1,
    votes: 678,
    views: 14200,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/gFZriCkpJYsApPcW5p0P0CwDp69.jpg",
    trailerUrl: "https://www.youtube.com/embed/3-kW_xIEbkI",
    genres: ["Містика", "Драма", "Трилер"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Хлопчик, який бачить мертвих людей, звертається за допомогою до психолога, щоб зрозуміти свої здібності.",
    tags: [],
    isNew: false,
    isPopular: true
  },
  {
    id: 35,
    title: "Титанік",
    year: 1997,
    duration: "3г 14хв",
    rating: 7.8,
    votes: 789,
    views: 18900,
    ageRating: "12+",
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2ow8YYM8FOQ8B2QQW2K4aJ.jpg",
    trailerUrl: "https://www.youtube.com/embed/CHYlDqV6tEY",
    genres: ["Мелодрама", "Драма", "Романтика"],
    countries: ["США"],
    translation: "Дубляж",
    description: "Епічна романтична драма про любов двох людей на борту легендарного корабля Титанік.",
    tags: [],
    isNew: false,
    isPopular: true
  }
];

// Отримати всі унікальні жанри
function getAllGenres() {
  const genres = new Set();
  MOVIES_DATA.forEach(m => m.genres.forEach(g => genres.add(g)));
  return Array.from(genres).sort();
}

// Отримати всі унікальні роки
function getAllYears() {
  const years = new Set();
  MOVIES_DATA.forEach(m => years.add(m.year));
  return Array.from(years).sort((a, b) => b - a);
}

// Отримати всі унікальні країни
function getAllCountries() {
  const countries = new Set();
  MOVIES_DATA.forEach(m => m.countries.forEach(c => countries.add(c)));
  return Array.from(countries).sort();
}

// Отримати фільм по ID
function getMovieById(id) {
  return MOVIES_DATA.find(m => m.id === parseInt(id));
}

// Фільтрувати фільми
function filterMovies({ genre, year, country, search, tag } = {}) {
  return MOVIES_DATA.filter(m => {
    if (genre && !m.genres.includes(genre)) return false;
    if (year && m.year !== parseInt(year)) return false;
    if (country && !m.countries.includes(country)) return false;
    if (tag && !m.tags.includes(tag)) return false;
    if (search) {
      const q = search.toLowerCase();
      if (!m.title.toLowerCase().includes(q) &&
          !m.description.toLowerCase().includes(q) &&
          !m.genres.some(g => g.toLowerCase().includes(q))) return false;
    }
    return true;
  });
}

// Отримати схожі фільми (по жанру)
function getSimilarMovies(movie, limit = 8) {
  return MOVIES_DATA
    .filter(m => m.id !== movie.id && m.genres.some(g => movie.genres.includes(g)))
    .sort(() => Math.random() - 0.5)
    .slice(0, limit);
}

// Отримати рекомендовані фільми
function getRecommendedMovies(movie, limit = 4) {
  return MOVIES_DATA
    .filter(m => m.id !== movie.id && m.isPopular)
    .sort(() => Math.random() - 0.5)
    .slice(0, limit);
}
